// 凭据 / 开发者设置一族（/settings/credentials、/settings/apps、/settings/developers、
// /settings/tokens、/settings/personal-access-tokens）实机文本与属性回归。
//
// 边界强度：**途径 A 实证**（2026-09-27 维护者从 popup 开发者模式导出的漏翻清单，
// schema github-zh-misses/1，五条 path 各一份），没有途径 B（Console 逐节点采集）的证据，
// 故按「导出条目本身就是一个文本节点」登记；含内部换行的长条目按 normalizeKey 折叠空白
// 后的形态写。
//
// 这五页最关键的边界事实（都在下方断言里锁住）：
//   1. 经典令牌的说明句被「Basic Authentication」链接切成三段，句末的 `.` 是纯符号节点
//      （翻不了也不收）；
//   2. 「Tokens you have generated … access the <a>GitHub API</a>.」里的 `GitHub API`
//      是纯专名加缩写，译文无法含中文字系，保留英文——句子碎片各自成键、拼接后读通；
//   3. 凭据总览卡片的计数行（`0 keys` / `3 tokens` / `18 OAuth apps` / `4 GitHub Apps`）
//      数字是动态值，走 `settings/credentials-*-count` 规则；
//   4. 令牌行的过期日期节点是 `on Fri, Nov 27 2026` / `on Wed, Sep  2 2026`
//      （周几缩写 + 月份缩写 + **空格补齐的日**、年份前无逗号），走 `settings/expires-on-*`
//      规则——月份无法经捕获组映射成中文，故 12 个月份全展开，周几在中文里不体现；
//   5. 属性只走精确命中：删除弹窗的 `Close dialog` / `Confirm token deletion` 与权限范围
//      芯片的 title 都是定值，可收；芯片上的**标识符本身不译**（见下）。
//
// 刻意**不收录**（下方反例断言）：
//   - OAuth 权限范围标识符（`repo` / `user` / `workflow` / `gist` / `notifications` /
//     `project` / `copilot` / `codespace` / `audit_log` / `admin:*` / `read:*` /
//     `write:*` / `delete:*`）：它们是 API 里的字面量，译了反而与代码和文档对不上；
//   - 用户内容：令牌名 `SNAKE_TOKEN` / `Refined GitHub` / `Zcode`、邮箱、
//     `M. Oppenheymu` / `(Oppenheymu)` / `@Oppenheymu`；
//   - 纯专名 / 缩写：`GitHub`、`Copilot`、`GitHub API`。
// 未命中即保留英文，这才是正确做法。
import { describe, expect, it } from "bun:test";
import { buildView } from "../../../../content/view.ts";
import { translateText } from "../../../../content/walker.ts";
import { dictCore, dictForLocale } from "../../../index.ts";

/** 按路径取该页的合并视图（pages/settings + global） */
function viewFor(pathname: string) {
	return buildView(
		pathname,
		dictForLocale("zh-CN"),
		new Map(Object.entries(dictCore.aliases)),
	);
}

const credentialsView = viewFor("/settings/credentials");
const appsView = viewFor("/settings/apps");
const developersView = viewFor("/settings/developers");
const tokensView = viewFor("/settings/tokens");
const patView = viewFor("/settings/personal-access-tokens");

/** /settings/credentials 的实机文本节点 */
const CREDENTIALS_NODES: readonly string[] = [
	"View and manage all the credentials generated or authorized by your personal account.",
	"Authorized GitHub Apps",
	"GitHub Apps that have been authorized to access your account.",
	"Authorized OAuth apps",
	"OAuth apps that have been authorized to access your account.",
	"Fine-grained personal access tokens",
	"Fine-grained personal access tokens generated by your personal account.",
	"Personal access tokens (classic)",
	"Personal access tokens (classic) generated by your personal account.",
	"SSH keys associated with your account.",
	// 卡片计数行（规则覆盖）
	"0 keys",
	"3 tokens",
	"18 OAuth apps",
	"4 GitHub Apps",
];

/** /settings/developers 的实机文本节点（含开发者设置侧栏） */
const DEVELOPERS_NODES: readonly string[] = [
	"Developer Settings",
	"OAuth Apps",
	"Developer applications",
	"New OAuth app",
	"No OAuth apps",
	"OAuth apps are used to access the GitHub API. Read the docs to find out more.",
	"View documentation",
	// 侧栏的三条令牌入口
	"Personal access tokens",
	"Fine-grained tokens",
	"Tokens (classic)",
];

/** /settings/personal-access-tokens 的实机文本节点 */
const PAT_NODES: readonly string[] = [
	"Fine-grained Personal Access Tokens",
	"Fine-grained personal access tokens",
	"Need an API token for scripts or testing? Generate a personal access token for quick access to the GitHub API.",
	"No fine-grained tokens created",
];

/** /settings/tokens 的实机文本节点 */
const TOKENS_NODES: readonly string[] = [
	"Personal Access Tokens (Classic)",
	"Personal access tokens (classic)",
	// 说明句三段（句首片段 + 链接 + 句末的纯符号节点 "."）
	"Personal access tokens (classic) function like ordinary OAuth access tokens. They can be used instead of a password for Git over HTTPS, or can be used to",
	"authenticate to the API over Basic Authentication",
	// 「…access the <a>GitHub API</a>.」
	"Tokens you have generated that can be used to access the",
	"Generate new token",
	"Generate new token (classic)",
	"Expires",
	"Expired",
	"This token has no expiration date",
	"Last used within the last week",
	"Last used within the last 2 months",
	"Last used within the last 6 months",
	"Fine-grained, repo-scoped",
	"For general use",
	// 删除弹窗
	"Are you sure you want to delete this token?",
	"I understand, delete this token",
	"Any applications or scripts using this token will no longer be able to access the GitHub API. You cannot undo this action.",
	// 过期日期节点（规则覆盖）
	"on Fri, Nov 27 2026",
	"on Wed, Sep  2 2026",
];

/** 权限范围芯片的 title（人类可读说明，属性；芯片上的标识符本身不译） */
const SCOPE_TITLES: readonly string[] = [
	"Full control of private repositories",
	"Full control of audit log",
	"Full control of codespaces",
	"Full control of enterprises",
	"Full control of github copilot settings and seat assignments",
	"Full control of organization hooks",
	"Full control of orgs and teams, read and write org projects",
	"Full control of projects",
	"Full control of public user gpg keys",
	"Full control of public user ssh signing keys",
	"Full control of repository hooks",
	"Full control of user public keys",
	"Read access of projects",
	"Read and write team discussions",
	"Update all user data",
	"Update github action workflows",
	"Access notifications",
	"Create gists",
	"Delete packages from github package registry",
	"Upload packages to github package registry",
	"Delete repositories",
	"Write org hosted compute network configurations",
];

/** 删除弹窗的两个无障碍属性（属性只走精确命中） */
const DIALOG_ATTRS: readonly string[] = [
	"Close dialog",
	"Confirm token deletion",
];

/**
 * 必须保持英文的实机节点：权限范围标识符（API 字面量）、用户内容与纯专名。
 * 它们都含拉丁字母、会通过「可翻译判定」，但收录即错。
 */
const MUST_STAY_ENGLISH: readonly string[] = [
	// OAuth 权限范围标识符（芯片上的字面量）
	"repo",
	"user",
	"workflow",
	"gist",
	"notifications",
	"project",
	"copilot",
	"codespace",
	"audit_log",
	"admin:enterprise",
	"admin:gpg_key",
	"admin:org",
	"admin:org_hook",
	"admin:public_key",
	"admin:repo_hook",
	"admin:ssh_signing_key",
	"read:project",
	"write:discussion",
	"write:network_configurations",
	"write:packages",
	"delete:packages",
	"delete_repo",
	// 用户内容（令牌名、用户名、邮箱）
	"SNAKE_TOKEN",
	"Refined GitHub",
	"Zcode",
	"oppenheymu@gmail.com",
	"M. Oppenheymu",
	"(Oppenheymu)",
	"@Oppenheymu",
	// 纯专名 / 缩写
	"GitHub",
	"Copilot",
	"GitHub API",
];

/** 节点在实机里通常带源码缩进与换行；两种形态都必须命中 */
function withWhitespace(node: string): readonly string[] {
	return [node, `\n        ${node}\n      `];
}

/**
 * 把一段实机节点序列按 walker 的语义过一遍：未命中的节点按原样保留，
 * 命中的节点写回译文并保留其首尾空白，最后拼接成页面上真实看到的那一行。
 */
function renderNodes(
	nodes: readonly string[],
	view: ReturnType<typeof viewFor>,
): string {
	return nodes
		.map((node) => {
			const translated = translateText(node, view);
			if (translated === null) return node;
			const lead = node.slice(
				0,
				node.length - node.trimStart().length,
			);
			const trail = node.slice(node.trimEnd().length);
			return `${lead}${translated}${trail}`;
		})
		.join("");
}

describe("凭据页（/settings/credentials）的实机节点边界", () => {
	it("translates every text node GitHub actually renders", () => {
		for (const node of CREDENTIALS_NODES) {
			for (const variant of withWhitespace(node)) {
				const translated = translateText(
					variant,
					credentialsView,
				);
				expect(
					translated,
					`未命中：${JSON.stringify(variant)}`,
				).not.toBeNull();
				expect(translated ?? "").toMatch(/[\u4e00-\u9fff]/);
			}
		}
	});

	it("renders the five credential cards", () => {
		expect(
			translateText(
				"View and manage all the credentials generated or authorized by your personal account.",
				credentialsView,
			),
		).toBe(
			"查看并管理由你的个人账户生成或授权的所有凭据。",
		);
		expect(
			translateText(
				"Authorized GitHub Apps",
				credentialsView,
			),
		).toBe("已授权的 GitHub 应用");
		expect(
			translateText(
				"GitHub Apps that have been authorized to access your account.",
				credentialsView,
			),
		).toBe("已获授权访问你账户的 GitHub 应用。");
		expect(
			translateText(
				"OAuth apps that have been authorized to access your account.",
				credentialsView,
			),
		).toBe("已获授权访问你账户的 OAuth 应用。");
		expect(
			translateText(
				"Fine-grained personal access tokens generated by your personal account.",
				credentialsView,
			),
		).toBe("由你的个人账户生成的细粒度个人访问令牌。");
		expect(
			translateText(
				"Personal access tokens (classic) generated by your personal account.",
				credentialsView,
			),
		).toBe("由你的个人账户生成的个人访问令牌（经典）。");
		expect(
			translateText(
				"SSH keys associated with your account.",
				credentialsView,
			),
		).toBe("与你的账户关联的 SSH 密钥。");
	});

	it("translates the card counters through the count rules", () => {
		expect(translateText("0 keys", credentialsView)).toBe(
			"0 个密钥",
		);
		expect(translateText("1 key", credentialsView)).toBe(
			"1 个密钥",
		);
		expect(translateText("3 tokens", credentialsView)).toBe(
			"3 个令牌",
		);
		expect(
			translateText("18 OAuth apps", credentialsView),
		).toBe("18 个 OAuth 应用");
		// 产品名 "GitHub Apps" 的 A 在实机里是大写
		expect(
			translateText("4 GitHub Apps", credentialsView),
		).toBe("4 个 GitHub 应用");
		expect(
			translateText("1 GitHub App", credentialsView),
		).toBe("1 个 GitHub 应用");
	});
});

describe("开发者设置页（/settings/developers、/settings/apps）的实机节点边界", () => {
	it("translates every text node GitHub actually renders", () => {
		for (const view of [developersView, appsView]) {
			for (const node of DEVELOPERS_NODES) {
				const translated = translateText(node, view);
				expect(
					translated,
					`未命中：${JSON.stringify(node)}`,
				).not.toBeNull();
				expect(translated ?? "").toMatch(/[\u4e00-\u9fff]/);
			}
		}
		// /settings/apps 只多一条页面标题，且与侧栏同键
		expect(translateText("GitHub Apps", appsView)).toBe(
			"GitHub 应用",
		);
	});

	it("renders the developer settings shell and the OAuth apps page", () => {
		expect(
			translateText("Developer Settings", developersView),
		).toBe("开发者设置");
		expect(
			translateText("OAuth Apps", developersView),
		).toBe("OAuth 应用");
		expect(
			translateText(
				"Developer applications",
				developersView,
			),
		).toBe("开发者应用");
		expect(
			translateText("New OAuth app", developersView),
		).toBe("新建 OAuth 应用");
		expect(
			translateText("No OAuth apps", developersView),
		).toBe("没有 OAuth 应用");
		expect(
			translateText(
				"OAuth apps are used to access the GitHub API. Read the docs to find out more.",
				developersView,
			),
		).toBe(
			"OAuth 应用用于访问 GitHub API。阅读文档了解更多。",
		);
		expect(
			translateText("View documentation", developersView),
		).toBe("查看文档");
		// 侧栏三条令牌入口（同键在凭据总览页也渲染）
		expect(
			translateText(
				"Personal access tokens",
				developersView,
			),
		).toBe("个人访问令牌");
		expect(
			translateText("Fine-grained tokens", developersView),
		).toBe("细粒度令牌");
		expect(
			translateText("Tokens (classic)", developersView),
		).toBe("令牌（经典）");
	});
});

describe("细粒度令牌页（/settings/personal-access-tokens）的实机节点边界", () => {
	it("translates every text node GitHub actually renders", () => {
		for (const node of PAT_NODES) {
			const translated = translateText(node, patView);
			expect(
				translated,
				`未命中：${JSON.stringify(node)}`,
			).not.toBeNull();
			expect(translated ?? "").toMatch(/[\u4e00-\u9fff]/);
		}
	});

	it("renders the page title and the empty state", () => {
		// 页面标题是 Title Case，与凭据卡片的小写形态是两个键、同一条译文
		expect(
			translateText(
				"Fine-grained Personal Access Tokens",
				patView,
			),
		).toBe("细粒度个人访问令牌");
		expect(
			translateText(
				"Fine-grained personal access tokens",
				patView,
			),
		).toBe("细粒度个人访问令牌");
		expect(
			translateText(
				"Need an API token for scripts or testing? Generate a personal access token for quick access to the GitHub API.",
				patView,
			),
		).toBe(
			"需要用于脚本或测试的 API 令牌？生成个人访问令牌即可快速访问 GitHub API。",
		);
		expect(
			translateText(
				"No fine-grained tokens created",
				patView,
			),
		).toBe("尚未创建细粒度令牌");
	});
});

describe("经典令牌页（/settings/tokens）的实机节点边界", () => {
	it("translates every text node GitHub actually renders", () => {
		for (const node of [
			...TOKENS_NODES,
			...SCOPE_TITLES,
			...DIALOG_ATTRS,
		]) {
			for (const variant of withWhitespace(node)) {
				const translated = translateText(
					variant,
					tokensView,
				);
				expect(
					translated,
					`未命中：${JSON.stringify(variant)}`,
				).not.toBeNull();
				expect(translated ?? "").toMatch(/[\u4e00-\u9fff]/);
			}
		}
	});

	it("keeps scope identifiers, token names and brand names as-is", () => {
		for (const raw of MUST_STAY_ENGLISH) {
			expect(
				translateText(raw, tokensView),
				`不应被翻译：${JSON.stringify(raw)}`,
			).toBeNull();
		}
	});

	it("renders the classic-token blurb across its link boundary", () => {
		// 实机：`… or can be used to <a>authenticate to the API over Basic Authentication</a>.`
		// ——`. ` 之前的片段与链接各成节点，句末的 "." 是纯符号节点
		const rendered = renderNodes(
			[
				"Personal access tokens (classic) function like ordinary OAuth access tokens. They can be used instead of a password for Git over HTTPS, or can be used to",
				" ",
				"authenticate to the API over Basic Authentication",
				".",
			],
			tokensView,
		);
		expect(rendered).toBe(
			"个人访问令牌（经典）的作用类似于普通的 OAuth 访问令牌。它们可在通过 HTTPS 使用 Git 时代替密码，也可用于 通过基本身份验证向 API 进行身份验证.",
		);
		// 链接「GitHub API」保持英文：整句拼接后仍然是通顺的中文
		expect(
			renderNodes(
				[
					"Tokens you have generated that can be used to access the",
					" ",
					"GitHub API",
					".",
				],
				tokensView,
			),
		).toBe("你生成的、可用于访问 GitHub API.");
	});

	it("translates the expiry label and every month of the expiry date rule", () => {
		expect(translateText("Expires", tokensView)).toBe(
			"过期时间",
		);
		expect(translateText("Expired", tokensView)).toBe(
			"已过期",
		);
		expect(
			translateText(
				"This token has no expiration date",
				tokensView,
			),
		).toBe("此令牌没有过期日期");
		// 实机节点：`Expires ` + `on Fri, Nov 27 2026`
		expect(
			renderNodes(
				["Expires", " ", "on Fri, Nov 27 2026"],
				tokensView,
			),
		).toBe("过期时间 2026 年 11 月 27 日");
		// 日被空格补齐（"Sep  2"）、周几与年份都要吃对
		const months = [
			["Jan", "1"],
			["Feb", "2"],
			["Mar", "3"],
			["Apr", "4"],
			["May", "5"],
			["Jun", "6"],
			["Jul", "7"],
			["Aug", "8"],
			["Sep", "9"],
			["Oct", "10"],
			["Nov", "11"],
			["Dec", "12"],
		] as const;
		for (const [month, cn] of months) {
			expect(
				translateText(
					`on Wed, ${month}  2 2026`,
					tokensView,
				),
			).toBe(`2026 年 ${cn} 月 2 日`);
		}
		expect(
			translateText("on Wed, Sep  2 2026", tokensView),
		).toBe("2026 年 9 月 2 日");
	});

	it("renders the delete-token dialog", () => {
		expect(
			translateText(
				"Are you sure you want to delete this token?",
				tokensView,
			),
		).toBe("你确定要删除这个令牌吗？");
		expect(
			translateText(
				"Any applications or scripts using this token will no longer be able to access the GitHub API. You cannot undo this action.",
				tokensView,
			),
		).toBe(
			"任何使用此令牌的应用或脚本将无法再访问 GitHub API。此操作无法撤销。",
		);
		expect(
			translateText(
				"I understand, delete this token",
				tokensView,
			),
		).toBe("我明白，删除这个令牌");
		// 两个无障碍属性（精确命中）
		expect(translateText("Close dialog", tokensView)).toBe(
			"关闭对话框",
		);
		expect(
			translateText("Confirm token deletion", tokensView),
		).toBe("确认删除令牌");
	});

	it("translates the scope tooltips but keeps the scope chips in English", () => {
		// 芯片上的标识符不译（API 字面量），title 里的人类可读说明要译
		expect(
			translateText(
				"Full control of private repositories",
				tokensView,
			),
		).toBe("完全控制私有仓库");
		expect(translateText("Create gists", tokensView)).toBe(
			"创建 Gist",
		);
		expect(
			translateText(
				"Full control of orgs and teams, read and write org projects",
				tokensView,
			),
		).toBe("完全控制组织和团队，读写组织项目");
		expect(translateText("repo", tokensView)).toBeNull();
		expect(
			translateText("admin:org", tokensView),
		).toBeNull();
	});
});
